# Generated by Django 5.2.8 on 2025-12-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_stop_loss_order_take_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_history', to='main.asset')),
            ],
            options={
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]
