# Generated by Django 6.0 on 2026-01-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_asset_symbol_marketdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_auto_pilot',
            field=models.BooleanField(default=False),
        ),
    ]
