# Generated by Django 6.0 on 2026-01-07 11:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userautopilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userautopilot',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10),
        ),
        migrations.AddField(
            model_name='userautopilot',
            name='stop_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='userautopilot',
            name='take_profit_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
    ]
